
["Shutdowner settings"]

	["Shutdowner settings"."server shutdown hang settings"]
		#Whether to kill the server when shutdown takes too long. default: true
		shouldDetectShutDownHang = true
		#The maximum time the shutdown is allowed to take. default: 120s
		#Range: 1 ~ 20000
		maxShutDownTime = 300
		#Print remaining threads to log? default:true
		printThreads = true

	["Shutdowner settings"."server timed shutdown settings"]
		#Whether to use the timed shutdown default: true
		shouldAutoShutDown = true
		#Set the disconnect message for the players
		disconnectMessage = "Server re-booting."
		#Shutdown timepoints,, format: ["time1","time2"] e.g. ["18:00","23:00"]
		shutdownTimes = ["00:00", "12:00"]
		#Shutting down timed messages, format: [secondsToShutdown;Message] e.g. ["300;Server is restarting in 5min","150;Server is restarting in 2.5min"]
		shutdownMessages = ["300;Server is restarting in 5 minutes", "180;3 minutes until shutdown", "120;2 minutes until shutdown", "60;1 minute until shutdown", "30;30 seconds until shutdown", "10;10 seconds until shutdown", "9;9", "8;8", "7;7", "6;6", "5;5", "4;4", "3;3", "2;2", "1;1", "0;Shutting down now"]

	["Shutdowner settings"."server runtime hang settings"]
		#Whether to detect and close the server hang during runtime default: true
		shouldDetectHang = true

